#!/bin/bash -x

# This is as bare-bones as you can get.
# Individual service failures are not caught.
# Terminate the container to recover from such issues.
# User-provided configs can cause container failures. Make sure your configs are solid.
# To do: make this robust, maybe with a supervisor.

# Start MySQL/MariaDB
nohup /usr/bin/mysqld_safe --datadir="/var/lib/mysql" &
# Since we break off, we need to give it time to start up.
sleep 3

# Import the custom unRAID device templates
#/usr/bin/php /usr/share/webapps/cacti/cli/import_template.php --filename=/unRAID-Server.xml --profile-id=3
#/usr/bin/php /usr/share/webapps/cacti/cli/import_template.php --filename=/Net-SNMP-Memory-Usage.xml --profile-id=3 --remove-orphans
#/usr/bin/php /usr/share/webapps/cacti/cli/import_template.php --filename=/Net-SNMP-CPU-Utilization.xml --profile-id=3 --remove-orphans
#/usr/bin/php /usr/share/webapps/cacti/cli/import_template.php --filename=/Net-SNMP-Load-Average.xml --profile-id=3 --remove-orphans

# Start cron
# The cacti package installation left a cron file at: /etc/crontabs/cacti
# Also see: /var/spool/cron/crontabs/root, or just crontab -e
crond -L /var/log/cron

# Start Apache
/usr/sbin/httpd -k start -f /etc/apache2/httpd.conf

# Hold open the session
tail -F /var/log/apache2/error.log /var/log/apache2/access.log /var/log/cron /var/log/cacti/cacti.log /var/lib/mysql/${CONTAINERFQDN}.err